from robosuite.environments.base import make

# environments
from hiera_diffusion_policy.env.nonprehensile.rsuite.environments.manipulation_grasp import ManipulationGrasp
from hiera_diffusion_policy.env.nonprehensile.rsuite.environments.triangular_prism_lift import TriangularPrismLift
from hiera_diffusion_policy.env.nonprehensile.rsuite.environments.pusht3d import PushT3D

from hiera_diffusion_policy.env.nonprehensile.rsuite.models.grippers import ALL_GRIPPERS